import { FormEvent, StrictMode, useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Overview = { recon_sessions: number; honeypot_events: number; collector_events: number; top_paths: {path:string;hits:number}[]; countries:{country:string;hits:number}[] };
const api = async (path: string, options: RequestInit = {}) => {
  const response = await fetch(path, { credentials: 'same-origin', headers: {...(options.headers || {})}, ...options });
  if (!response.ok) throw new Error((await response.json().catch(() => ({detail:'Request failed.'}))).detail);
  return response.status === 204 ? null : response.json();
};
const sessionId = () => crypto.randomUUID().replaceAll('-', '');
const locale = navigator.language.toLowerCase().startsWith('es') ? 'es' : 'en';
const copy = {
  es: { privacy:'Privacidad', security:'Seguridad', login:'Iniciar sesión', footer:'Uso exclusivo en infraestructura propia o autorizada.', lab:'Laboratorio de telemetría para infraestructura autorizada.', collecting:'Recolección en curso.', preparing:'Preparando Recon…', asking:'El navegador está solicitando tu ubicación precisa…', recorded:'Recon y ubicación precisa registrados.', noLocation:'Recon registrado sin ubicación precisa.', unavailable:'Recon registrado; este navegador no ofrece geolocalización.', reconNote:'El registro comienza automáticamente. El navegador solicitará ubicación precisa; puedes permitirla o rechazarla.', admin:'Acceso administrativo', email:'Correo electrónico', loginHint:'Local: admin / admin', password:'Contraseña', enter:'Entrar', dashboard:'Dashboard', logout:'Salir', loading:'Cargando…', overview:'Resumen', events:'Eventos', collectors:'Collectors', scripts:'Scripts', recon:'Recon', terms:'Términos', privacyText:'Recon almacena metadatos HTTP permitidos y capacidades del navegador. GeoIP es aproximado. Al abrir Recon, el navegador muestra un permiso para ubicación precisa; solo se almacena si lo concedes y se retiene por un periodo limitado.', termsText:'Utiliza CyberLab únicamente en sistemas propios o con autorización explícita.', securityText:'No envíes secretos ni datos sensibles. Reporta vulnerabilidades al administrador del servicio.', reconCount:'Recon', honeypot:'Honeypot', paths:'Paths frecuentes', geo:'GeoIP aproximado', forbidden:'Acceso prohibido.', internalError:'Error interno del servidor.', notFound:'Recurso no encontrado.' },
  en: { privacy:'Privacy', security:'Security', login:'Sign in', footer:'Use only on infrastructure you own or are authorized to assess.', lab:'Telemetry lab for authorized infrastructure.', collecting:'Collection in progress.', preparing:'Preparing Recon…', asking:'Your browser is requesting precise location…', recorded:'Recon and precise location recorded.', noLocation:'Recon recorded without precise location.', unavailable:'Recon recorded; this browser does not provide geolocation.', reconNote:'Collection starts automatically. Your browser will request precise location; you may allow or deny it.', admin:'Administrative access', email:'Email address', loginHint:'Local: admin / admin', password:'Password', enter:'Sign in', dashboard:'Dashboard', logout:'Sign out', loading:'Loading…', overview:'Overview', events:'Events', collectors:'Collectors', scripts:'Scripts', recon:'Recon', terms:'Terms', privacyText:'Recon stores permitted HTTP metadata and browser capabilities. GeoIP is approximate. When Recon opens, the browser presents a precise-location permission request; it is stored only if you allow it and retained for a limited time.', termsText:'Use CyberLab only on systems you own or have explicit authorization to assess.', securityText:'Do not send secrets or sensitive data. Report security issues to the service administrator.', reconCount:'Recon', honeypot:'Honeypot', paths:'Frequent paths', geo:'Approximate GeoIP', forbidden:'Access forbidden.', internalError:'Internal server error.', notFound:'Resource not found.' },
}[locale];

function Layout({children}:{children:React.ReactNode}) { return <><header><a className="brand" href="/">CyberLab Server</a><nav><a href="/privacy">{copy.privacy}</a><a href="/security">{copy.security}</a><a href="/login">{copy.login}</a></nav></header>{children}<footer>{copy.footer}</footer></>; }

function Home() { return <Layout><main className="hello-page"><div className="hello-orb" aria-hidden="true" /><p className="eyebrow">CYBERLAB SERVER</p><h1 className="hello-word">Hello<span>.</span></h1><p>{copy.lab}</p></main></Layout>; }

function Recon() {
  const [status, setStatus] = useState(copy.preparing); const sent = useRef(false);
  const browser = useMemo(() => ({ screen: `${screen.width}x${screen.height}`, viewport: `${innerWidth}x${innerHeight}`, device_pixel_ratio: devicePixelRatio, language: navigator.language, languages: navigator.languages, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, cpu_cores: navigator.hardwareConcurrency ?? null, device_memory_gb: (navigator as Navigator & {deviceMemory?:number}).deviceMemory ?? null, touch_points: navigator.maxTouchPoints, cookies_enabled: navigator.cookieEnabled, do_not_track: navigator.doNotTrack ?? null, secure_context: isSecureContext, websocket: 'WebSocket' in window, webgl: !!document.createElement('canvas').getContext('webgl'), webgl2: !!document.createElement('canvas').getContext('webgl2'), webgpu: 'gpu' in navigator, indexeddb: 'indexedDB' in window, local_storage: (() => { try { return !!localStorage; } catch { return false; } })(), session_storage: (() => { try { return !!sessionStorage; } catch { return false; } })(), service_worker: 'serviceWorker' in navigator, notifications: 'Notification' in window, clipboard: !!navigator.clipboard, performance: !!window.performance }), []);
  useEffect(() => {
    if (sent.current) return;
    sent.current = true;
    const record = async (location: unknown, message: string) => {
      try { await api('/api/recon', {method:'POST', body:JSON.stringify({session_id:sessionId(), browser, location})}); setStatus(message); }
      catch (error) { setStatus(error instanceof Error ? error.message : 'Error inesperado.'); }
    };
    if (!navigator.geolocation) { record({permission_state:'unavailable'}, copy.unavailable); return; }
    setStatus(copy.asking);
    navigator.geolocation.getCurrentPosition(
      (point) => record({latitude:point.coords.latitude, longitude:point.coords.longitude, accuracy:point.coords.accuracy, timestamp:point.timestamp, permission_state:'granted'}, copy.recorded),
      () => record({permission_state:'denied'}, copy.noLocation),
      {enableHighAccuracy:true, timeout:10_000, maximumAge:60_000},
    );
  }, [browser]);
  return <Layout><main className="hello-page"><div className="hello-orb" aria-hidden="true" /><p className="eyebrow">CYBERLAB SERVER</p><h1 className="hello-word">Recon<span>.</span></h1><p>{copy.collecting}</p><p role="status">{status}</p></main></Layout>;
}

function StaticPage({title, children}:{title:string;children:React.ReactNode}) { return <Layout><main><h1>{title}</h1><div className="card">{children}</div></main></Layout>; }
function Login({onLogin}:{onLogin:()=>void}) { const [error,setError]=useState(''); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const data=new FormData(e.currentTarget); const submittedUsername=String(data.get('username')).trim(); const username=submittedUsername === 'admin' ? 'admin@example.com' : submittedUsername; try {await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({username,password:String(data.get('password'))})});onLogin();}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.')}}; return <Layout><main className="narrow"><h1>{copy.admin}</h1><form className="card" onSubmit={submit}><label>{copy.email}<input name="username" type="text" autoComplete="username" required /></label><p>{copy.loginHint}</p><label>{copy.password}<input name="password" type="password" autoComplete="current-password" required /></label><button className="primary">{copy.enter}</button><p role="alert">{error}</p></form></main></Layout>; }
function Dashboard() { const [authenticated,setAuthenticated]=useState<boolean|null>(null); const [overview,setOverview]=useState<Overview|null>(null); const [tab,setTab]=useState('overview'); const [data,setData]=useState<unknown[]>([]); const [error,setError]=useState(''); const labels:Record<string,string>={overview:copy.overview,recon:copy.recon,events:copy.events,collectors:copy.collectors,scripts:copy.scripts}; const load=async(t:string)=>{setTab(t);setError('');try{if(t==='overview')setOverview(await api('/api/admin/overview'));else {const result=await api(`/api/admin/${t}`);setData(result[t] ?? []);}}catch(e){setError(e instanceof Error?e.message:'Error');}}; useEffect(()=>{api('/api/auth/me').then(()=>{setAuthenticated(true);load('overview');}).catch(()=>setAuthenticated(false));},[]); if(authenticated===null)return <Layout><main>{copy.loading}</main></Layout>; if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)} />; return <Layout><main><div className="dashboard-title"><h1>{copy.dashboard}</h1><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});setAuthenticated(false);}}>{copy.logout}</button></div><div className="tabs">{Object.keys(labels).map(t=><button key={t} onClick={()=>load(t)} className={tab===t?'active':''}>{labels[t]}</button>)}</div>{error&&<p role="alert">{error}</p>}{tab==='overview'&&overview&&<><section className="metrics"><article><b>{overview.recon_sessions}</b>{copy.reconCount}</article><article><b>{overview.honeypot_events}</b>{copy.honeypot}</article><article><b>{overview.collector_events}</b>{copy.collectors}</article></section><section className="grid"><div className="card"><h2>{copy.paths}</h2>{overview.top_paths.map(x=><p key={x.path}><code>{x.path}</code> · {x.hits}</p>)}</div><div className="card"><h2>{copy.geo}</h2>{overview.countries.map(x=><p key={x.country}>{x.country} · {x.hits}</p>)}</div></section></>}{tab!=='overview'&&<pre className="card">{JSON.stringify(data,null,2)}</pre>}</main></Layout>; }
function App(){const path=location.pathname; if(path==='/')return <Home/>; if(path==='/recon')return <Recon/>; if(path==='/login')return <Dashboard/>; if(path==='/dashboard'||path.startsWith('/dashboard/'))return <Dashboard/>; if(path==='/privacy')return <StaticPage title={copy.privacy}><p>{copy.privacyText}</p></StaticPage>; if(path==='/terms')return <StaticPage title={copy.terms}><p>{copy.termsText}</p></StaticPage>; if(path==='/security')return <StaticPage title={copy.security}><p>{copy.securityText}</p></StaticPage>; if(path==='/403')return <StaticPage title="403"><p>{copy.forbidden}</p></StaticPage>; if(path==='/500')return <StaticPage title="500"><p>{copy.internalError}</p></StaticPage>; return <StaticPage title="404"><p>{copy.notFound}</p></StaticPage>;}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
