table inet impacket_killswitch {
    chain forward {
        type filter hook forward priority -10; policy accept;

        # Impacket puede alcanzar únicamente la LAN autorizada directamente.
        iifname "impacketbr0" ip saddr 172.32.0.2 ip daddr 192.168.100.0/24 oifname "wlp6s0" accept

        # Toda otra salida directa por Wi-Fi queda bloqueada.
        iifname "impacketbr0" ip saddr 172.32.0.2 oifname "wlp6s0" drop
    }
}
