table inet enum4linux_killswitch {
    chain forward {
        type filter hook forward priority -10; policy accept;

        # enum4linux-ng puede alcanzar únicamente la LAN autorizada directamente.
        iifname "enum4linuxbr0" ip saddr 172.31.0.2 ip daddr 192.168.100.0/24 oifname "wlp6s0" accept

        # Toda otra salida directa por Wi-Fi queda bloqueada.
        iifname "enum4linuxbr0" ip saddr 172.31.0.2 oifname "wlp6s0" drop
    }
}
